In [11]:
import torch


In [25]:
!nvidia-smi

Sat Jan 25 21:06:14 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti     Off | 00000000:01:00.0  On |                  N/A |
| N/A   40C    P8              N/A /  16W |    131MiB /  4096MiB |     15%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [13]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [14]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {device}")
# Create two random tensors on GPU
tensor_gpu_A = torch.rand(2,3).to(device)
tensor_gpu_B = torch.rand(2,3).to(device)

tensor_gpu_A, tensor_gpu_B


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [16]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_gpu_A, tensor_gpu_B.T)
result, result.shape



(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [17]:
# Find max
print(f"Max: {result.max()}")
# Find min
print(f"Min: {result.min()}")


Max: 0.5617256760597229
Min: 0.3647301495075226


In [19]:
# Find arg max
max_index = torch.argmax(result)

# Find arg min
min_index = torch.argmin(result)

max_index, min_index


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_A = torch.rand(1,1,1,10)

# Remove single dimensions
random_B = random_A.squeeze()

# Print out tensors and their shapes
print(random_A, random_A.shape)
print(random_B, random_B.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
